language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev"
  - "3.6-dev"
  - "nightly"
  - "pypy"
  - "pypy3"

install:
 - pip install -r requirements-test.txt
 - pip install nose coverage

script:
 - make test

after_script:
 - coveralls
