language: python

python:
  - "3.3"
  - "3.2"
  - "2.7"
  - "2.6"
  - "pypy"

install:
 - pip install -r requirements-test.txt

script:
 - coverage run --source=podcastparser test.py

after_script:
 - coveralls
